name: "Workflow Example"

on:
  push:
    branches:
      - "main"

jobs:
  example:
    runs-on: ubuntu-20.04
    steps:
    steps:
      - uses: opentofu/setup-opentofu@v1
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

      - name: Test
        run: |
          tenv version
          tenv tf install latest


      # - uses: tofuutils/tenv-github-action@main
      #   with:
      #     tool_name: terraform
      #     tool_version: 1.5.7
      # - name: Test terraform
      #   run: |
      #     ls -lah $GITHUB_WORKSPACE/.tenv
      #     ls -lah ~/.tenv
      #     ls -lah .tenv
      #     terraform version

      # - uses: tofuutils/tenv-github-action@main
      #   with:
      #     tool_name: tofu
      #     tool_version: 1.8.0

      # - name: Test OpenTofu
      #   run: tofu version
